name: firefit
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.1+23

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_crashlytics: ^2.4.3

  rxdart: ^0.27.3
  path_provider: ^2.0.7

  firebase_messaging: ^11.1.0
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0
  flutter_inner_drawer: ^1.0.0+1
  cached_network_image: ^3.1.0+1
  flutter_swiper: ^1.1.6
  carousel_slider: ^4.0.0
  multi_image_picker: ^4.5.2
  validate: ^1.7.0
  overlay_support: ^1.0.0
  extended_image: ^5.1.3
  country_code_picker: ^2.0.2
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_rating_bar: ^4.0.0
  pull_to_refresh: ^2.0.0
  firebase_analytics: ^9.0.3
  firebase_admob: ^0.11.2
  firebase_remote_config: ^1.0.2
  page_transition: ^2.0.4
  package_info: ^2.0.2
  share: ^2.0.4
  notification_permissions: ^0.6.1
  url_launcher: ^6.0.5
  permission_handler: ^8.3.0
  flutter_inapp_purchase: ^5.1.2

  intl: ^0.17.0
  meta:
  html_unescape: ^2.0.0

  # Firebase services
  cloud_functions: ^3.1.1
  firebase_auth: ^3.2.0
  firebase_storage: ^10.1.0
  sqlbrite: ^2.0.0
  sqflite: ^2.0.0+3
  flutter_image_compress: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/style/
   - assets/splash/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
