name: repository_impl
description: A reactive implementation of the repository for Flutter using firebase

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  middleware:
    path: ../middleware
  helpers:
    path: ../helpers
# Firebase services    
  cloud_functions: ^0.4.0
  firebase_auth: ^0.11.1+6
  firebase_storage: ^3.0.1
  streamqflite: ^1.0.0
  firebase_messaging: ^5.0.3
  flutter_image_compress: ^0.2.4
  firebase_analytics: ^3.0.3

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
