name: repository_impl
description: A reactive implementation of the repository for Flutter using firebase

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  middleware:
    path: ../middleware
  helpers:
    path: ../helpers
# Firebase services    
  cloud_functions: ^0.0.5
  firebase_auth: ^0.6.6
  firebase_storage: ^1.0.4
  streamqflite: ^1.0.0
  firebase_messaging: ^2.1.0
  flutter_image_compress: ^0.2.4

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
