name: blocs
description: The Business Logic Components for firefit

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  helpers:
    path: ../helpers
  middleware:
    path: ../middleware
  rxdart: 0.18.0
  path_provider: ^1.2.0

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
