name: data_handler
description: An app-agnostic data source that can be used by all implementations

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta:
  html_unescape: ^1.0.1+2

dev_dependencies:
  mockito: ^3.0.0
